"""add is_primary to image table

Revision ID: 2311d35b2828
Revises: 31bfafb086b5
Create Date: 2014-10-29 01:33:51.775756

"""

# revision identifiers, used by Alembic.
revision = '2311d35b2828'
down_revision = '31bfafb086b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'image', sa.Column('is_primary', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'image', 'is_primary')
    ### end Alembic commands ###
