"""Add in new field post_type to post, also make price field nullable

Revision ID: 31bfafb086b5
Revises: 3821d3aa8ff3
Create Date: 2014-10-27 19:49:51.984796

"""

# revision identifiers, used by Alembic.
revision = '31bfafb086b5'
down_revision = '3821d3aa8ff3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'post', sa.Column('type_code', sa.SmallInteger(), nullable=True))
    op.alter_column(u'post', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'post', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_column(u'post', 'type_code')
    ### end Alembic commands ###
