"""modify chat table. Renaem seller/buyer to owner/contact

Revision ID: 4c288143fd16
Revises: 5a0110e162d8
Create Date: 2014-11-11 21:19:47.354869

"""

# revision identifiers, used by Alembic.
revision = '4c288143fd16'
down_revision = '5a0110e162d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'chat_ibfk_2',u'chat',type_=u"foreignkey")
    op.drop_constraint(u'chat_ibfk_3',u'chat',type_=u"foreignkey")
    
    op.alter_column(u'chat', 'seller_id', existing_type=sa.Integer(), new_column_name='owner_id')
    op.alter_column(u'chat', 'buyer_id',  existing_type=sa.Integer(),new_column_name='contact_id')
    op.alter_column(u'chat', 'seller_name', existing_type=sa.String(length=64),new_column_name='owner_name')
    op.alter_column(u'chat', 'buyer_name',  existing_type=sa.String(length=64),new_column_name='contact_name')
    op.alter_column(u'chat', 'seller_read', existing_type=sa.SmallInteger(),new_column_name='owner_read')
    op.alter_column(u'chat', 'buyer_read',  existing_type=sa.SmallInteger(),new_column_name='contact_read')
    op.create_foreign_key("chat_ibfk_4", u'chat', 'user', ['owner_id'], ['id'])
    op.create_foreign_key("chat_ibfk_5", u'chat', 'user', ['contact_id'], ['id'])
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(u'chat_ibfk_4',u'chat',type_=u"foreignkey")
    #op.drop_constraint(u'chat_ibfk_5',u'chat',type_=u"foreignkey")
    
    op.alter_column(u'chat', 'owner_id',   existing_type=sa.Integer(), new_column_name='seller_id')
    op.alter_column(u'chat', 'contact_id', existing_type=sa.Integer(), new_column_name='buyer_id')
    op.alter_column(u'chat', 'owner_name',  existing_type=sa.String(length=64),new_column_name='seller_name')
    op.alter_column(u'chat', 'contact_name', existing_type=sa.String(length=64),new_column_name='buyer_name')
    op.alter_column(u'chat', 'owner_read',   existing_type=sa.SmallInteger(),new_column_name='seller_read')
    op.alter_column(u'chat', 'contact_read', existing_type=sa.SmallInteger(),new_column_name='buyer_read')
    op.create_foreign_key("chat_ibfk_2", u'chat', 'user', ['seller_id'], ['id'])
    op.create_foreign_key("chat_ibfk_3", u'chat', 'user', ['buyer_id'], ['id'])
    ### end Alembic commands ###
