"""Add in post_bookmark table

Revision ID: 558bd3f07675
Revises: None
Create Date: 2014-10-12 15:49:21.127845

"""

# revision identifiers, used by Alembic.
revision = '558bd3f07675'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_code', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_bookmark')
    ### end Alembic commands ###
